!(register-module! ../../../Genetic-Algorithm)
!(import! &self Genetic-Algorithm:metta:utils)


!(max 4 5)
!(min 4 5)
!(maximum (0.9  0.9  0.0  0.8  0.2  0.9  0.7  0.7) (0.8  0.2  1.0  0.3  0.9  0.4  0.6  0.3))
!(minimum (0.9  0.9  0.0  0.8  0.2  0.9  0.7  0.7) (0.8  0.2  1.0  0.3  0.9  0.4  0.6  0.3))


!(reverse (4 5 )())
!(difference (0.9  0.9  0.0  0.8  0.2  0.9  0.7  0.7) (0.8  0.2  1.0  0.3  0.9  0.4  0.6  0.3))